"""
Name sticker generator — small icon+name labels (decal board D06/D13 family:
kids' name + sport/kawaii icon, e.g. bag/lunchbox/water-bottle tags).

Separate script from bin_sticker.py by design (not a modification of it) --
see chat history. Shares its architecture and a few small utilities
(recolour_silhouette, the vector-icon-fallback pattern, tick-mark alignment
guides) because those are genuinely reusable, not because this is meant to
grow into the same file.

CUTTING METHOD -- read this before changing CARD_W/CARD_H or CORNER_RADIUS:
This is a "cut only" job on the Explore 5, same principle as bin stickers --
NOT Cricut Print Then Cut. The label's outer shape (a fixed rounded
rectangle) is known in advance and never changes, regardless of what name
or icon is printed inside it, so Design Space doesn't need to trace/detect
it from registration marks. Workflow:
    1. Print sheet.pdf on the Epson (this script's output).
    2. Align the printed sheet on the Explore 5's mat using the corner tick
       marks this script draws (by eye, not a Cricut feature).
    3. Import cut_lines.svg (generated by generate_name_sticker_cut_lines.py
       -- separate paired script, same relationship as bin_sticker.py has
       with generate_cut_lines_dxf.py) into Design Space as a CUT ONLY job,
       not Print Then Cut.
    4. Cut.
This is why the full A4 usable area applies here (unlike the ~171-183 x
235-270mm Print-Then-Cut registration-mark boundary flagged in the decal
board for contour-shaped designs) -- a fixed rounded rect never needs that
detection step. If CARD_W/CARD_H/CORNER_RADIUS ever change, re-run
generate_name_sticker_cut_lines.py so the cut file and the printed sheet
stay in sync -- a mismatch here means the machine cuts in the wrong place.
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor, white
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from PIL import Image
import os

# ---------------------------------------------------------------------------
# Card geometry -- keep in sync with generate_name_sticker_cut_lines.py
# ---------------------------------------------------------------------------
CARD_W, CARD_H = 50 * mm, 25 * mm  # D06/D13 estimate: ~5 x 2.5cm
CORNER_RADIUS = 3 * mm             # built into the cut path itself, per
                                    # the "rounded rectangle" decision
GAP = 3 * mm                       # spacing between labels on the sheet
MARGIN = 10 * mm                   # sheet edge margin

GUIDE = "#CCCCCC"
BG = "#FFFFFF"
INK = "#222222"

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def _asset_path(rel_path):
    return os.path.join(_SCRIPT_DIR, rel_path)


# ---------------------------------------------------------------------------
# Font -- looks for a real TTF first (drop one at assets/fonts/, e.g. a
# Baloo 2 or Quicksand Bold export from Google Fonts, matching the font
# families already identified for this style in the decal board), falls
# back to core Helvetica-Bold with a one-time warning so the script is
# runnable and testable before the real font file is sourced.
# ---------------------------------------------------------------------------
NAME_FONT_TTF = "assets/fonts/NameFont-Bold.ttf"
_FONT_NAME = "Helvetica-Bold"
_font_warned = False


def _ensure_font():
    global _FONT_NAME, _font_warned
    ttf_path = _asset_path(NAME_FONT_TTF)
    if os.path.exists(ttf_path):
        if _FONT_NAME != "NameFont":
            pdfmetrics.registerFont(TTFont("NameFont", ttf_path))
            _FONT_NAME = "NameFont"
    elif not _font_warned:
        print(
            f"[name_sticker] No font found at {ttf_path} -- using "
            "Helvetica-Bold as a placeholder. Drop a real TTF there "
            "(e.g. Baloo 2 or Quicksand Bold, both free/OFL on Google "
            "Fonts) to match the intended look before printing real orders."
        )
        _font_warned = True


# ---------------------------------------------------------------------------
# Icon assets -- same cached-recolour pattern as bin_sticker.py's
# recolour_silhouette / _p02_icon_path, reused here rather than duplicated.
# Each entry is a single-colour transparent silhouette PNG, recoloured to
# the requested accent on first use and cached to disk. No real icon
# assets are sourced yet (see D06/D13 in the decal board -- Midjourney
# generation or a licensed pack, still an open item) so every key below
# falls back to the built-in vector star until a PNG actually exists at
# its path -- same "upgrades automatically once real art lands" pattern
# bin_sticker.py uses for house_banner.
# ---------------------------------------------------------------------------
ICON_ASSETS = {
    "star": "assets/icons/star_icon.png",
    "soccer_ball": "assets/icons/soccer_ball_icon.png",
    "skateboard": "assets/icons/skateboard_icon.png",
    "basketball": "assets/icons/basketball_icon.png",
    "sailboat": "assets/icons/sailboat_icon.png",
    # Extend this dict as real icon assets are sourced -- key name is
    # what `order["icon"]` should reference.
}


def recolour_silhouette(in_path, out_path, hex_color):
    """Recolours a single-colour silhouette PNG to any hex value, using
    its own alpha channel as the mask (identical to bin_sticker.py's
    version -- kept here too so this script has no import dependency on
    bin_sticker.py and can be handed off/run standalone)."""
    img = Image.open(in_path).convert("RGBA")
    r, g, b = tuple(int(hex_color.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4))
    pixels = img.load()
    for y in range(img.height):
        for x in range(img.width):
            _, _, _, a = pixels[x, y]
            if a > 0:
                pixels[x, y] = (r, g, b, a)
    img.save(out_path)


def draw_star_icon(c, cx, cy, size, color):
    """Vector fallback -- plain 5-point star, used until a real icon PNG
    exists for a given key. Not meant as final art for any real order."""
    import math
    c.saveState()
    c.setFillColor(HexColor(color))
    p = c.beginPath()
    outer_r, inner_r = size * 0.5, size * 0.2
    for i in range(10):
        r = outer_r if i % 2 == 0 else inner_r
        ang = math.radians(-90 + i * 36)
        x, y = cx + r * math.cos(ang), cy + r * math.sin(ang)
        if i == 0:
            p.moveTo(x, y)
        else:
            p.lineTo(x, y)
    p.close()
    c.drawPath(p, fill=1, stroke=0)
    c.restoreState()


def _draw_icon(c, cx, cy, size, color, icon_key):
    """Same single-switchover pattern as bin_sticker.py's _draw_icon: use
    the real PNG in ICON_ASSETS if it exists on disk, otherwise draw the
    vector star placeholder. Every icon_key falls back to the same star
    for now since no real icon set exists yet -- once assets land, every
    sticker using that key upgrades automatically, no other code change."""
    asset_path = ICON_ASSETS.get(icon_key)
    if asset_path and os.path.exists(_asset_path(asset_path)):
        cache_path = _asset_path(
            f"assets/icons/_cache_{icon_key}_{color.lstrip('#')}.png"
        )
        if not os.path.exists(cache_path):
            recolour_silhouette(_asset_path(asset_path), cache_path, color)
        img = ImageReader(cache_path)
        c.drawImage(img, cx - size / 2, cy - size / 2, size, size,
                    mask='auto', preserveAspectRatio=True)
    else:
        draw_star_icon(c, cx, cy, size, color)


# ---------------------------------------------------------------------------
# Base layer + alignment tick marks
# ---------------------------------------------------------------------------
def _draw_base(c, ox, oy, w=CARD_W, h=CARD_H, radius=CORNER_RADIUS):
    """White rounded-rect background + a thin grey guide outline so the
    printed sheet shows where the cut line WILL be (for visual reference
    only -- the actual cut path lives in the paired SVG file, this is not
    what the Cricut reads). Corner tick marks outside the shape for
    manual alignment on the mat, same convention as bin_sticker.py."""
    c.setFillColor(HexColor(BG))
    c.roundRect(ox, oy, w, h, radius, fill=1, stroke=0)

    c.setStrokeColor(HexColor(GUIDE))
    c.setLineWidth(0.4)
    c.roundRect(ox, oy, w, h, radius, fill=0, stroke=1)

    tick = 2.5 * mm
    for cx, cy, dx, dy in [
        (ox, oy, -tick, -tick), (ox + w, oy, tick, -tick),
        (ox, oy + h, -tick, tick), (ox + w, oy + h, tick, tick),
    ]:
        c.setStrokeColor(HexColor(GUIDE))
        c.setLineWidth(0.4)
        c.line(cx, cy, cx + dx, cy)
        c.line(cx, cy, cx, cy + dy)


def draw_label(c, ox, oy, order, w=CARD_W, h=CARD_H):
    """order = dict:
        name       str  (required)
        icon       key in ICON_ASSETS       (default "star")
        accent     hex colour str            (default "#2F6FA8")
    """
    _ensure_font()
    _draw_base(c, ox, oy, w, h)

    accent = order.get("accent", "#2F6FA8")
    icon_key = order.get("icon", "star")
    name = order.get("name", "")

    icon_size = h * 0.65
    icon_cx = ox + icon_size * 0.65
    icon_cy = oy + h / 2
    _draw_icon(c, icon_cx, icon_cy, icon_size, accent, icon_key)

    text_x = ox + icon_size * 1.25
    text_max_w = (ox + w - 2 * mm) - text_x
    font_size = 14
    c.setFont(_FONT_NAME, font_size)
    while pdfmetrics.stringWidth(name, _FONT_NAME, font_size) > text_max_w and font_size > 6:
        font_size -= 0.5
        c.setFont(_FONT_NAME, font_size)
    c.setFillColor(HexColor(INK))
    c.drawString(text_x, oy + h / 2 - font_size * 0.35, name)


# ---------------------------------------------------------------------------
# Sheet layout -- as many labels as fit on one A4 page, grid, full area
# available since this is cut-only (no Print-Then-Cut registration-mark
# boundary to work inside, unlike the contour-shaped designs elsewhere in
# the decal board).
# ---------------------------------------------------------------------------
def _grid_positions(card_w=CARD_W, card_h=CARD_H, gap=GAP, margin=MARGIN,
                     page_w=A4[0], page_h=A4[1]):
    cols = int((page_w - 2 * margin + gap) // (card_w + gap))
    rows = int((page_h - 2 * margin + gap) // (card_h + gap))
    total_w = cols * card_w + (cols - 1) * gap
    total_h = rows * card_h + (rows - 1) * gap
    start_x = (page_w - total_w) / 2
    start_y = (page_h - total_h) / 2
    positions = []
    for r in range(rows):
        for col in range(cols):
            x = start_x + col * (card_w + gap)
            y = page_h - start_y - card_h - r * (card_h + gap)
            positions.append((x, y))
    return positions, cols, rows


def render_sheet(orders, out_path):
    """orders: list of dicts (see draw_label). Fills as many A4 sheets as
    needed, same grid every page."""
    positions, cols, rows = _grid_positions()
    per_page = len(positions)
    c = canvas.Canvas(out_path, pagesize=A4)
    for i, order in enumerate(orders):
        slot = i % per_page
        if i > 0 and slot == 0:
            c.showPage()
        x, y = positions[slot]
        draw_label(c, x, y, order)
    c.showPage()
    c.save()
    print(f"{len(orders)} label(s) -> {out_path} "
          f"({cols}x{rows} = {per_page} per sheet, "
          f"{-(-len(orders) // per_page)} page(s))")


if __name__ == "__main__":
    sample_orders = [
        {"name": "Lucas", "icon": "soccer_ball", "accent": "#2F6FA8"},
        {"name": "Anna", "icon": "skateboard", "accent": "#B0532E"},
        {"name": "Maria", "icon": "basketball", "accent": "#B4841F"},
        {"name": "Sara", "icon": "sailboat", "accent": "#2F5233"},
    ]
    render_sheet(sample_orders, "/mnt/user-data/outputs/name_sticker_sheet.pdf")
