"""
Bin sticker generator — SHARED CORE — Kerbside Craft Co.

Split out Sep 2026 from the original single-file bin_sticker.py so each
print size can live in its own script (bin_sticker_small.py at
140x100mm, bin_sticker_medium.py at 210x140mm, and so on) without a bug
in one size's code risking the others. This module holds everything
that's genuinely size-agnostic: icon caching, accent palettes, the base
card + border drawing, plain vector icon shapes, font-fit/curved-text
helpers, and a generic grid sheet-layout function every size script
calls with its own card size and grid shape.

What does NOT live here: any style-drawing function, any per-style
pixel-measured constant (hollow icon positions, text centre-Y values,
etc.), and the STYLES/STYLE_LABELS/STYLE_PRODUCT_ID registries — those
are inherently per-size (a style's constants were measured against one
specific card size/aspect ratio) and belong in each size script.

Import this module from a size script with:
    import bin_sticker_core as core
or:
    from bin_sticker_core import *
"""

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor, white
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase.pdfmetrics import stringWidth
from PIL import Image
import os
import math
import tempfile
import atexit
import shutil

# ---------------------------------------------------------------------------
# Asset path resolution — resolved relative to THIS file's location, not
# whichever size script happens to be __main__. Every size script lives
# alongside this one and shares the same assets/ folder (recolouring is
# size-independent — the same master PNG gets drawn at whatever mm width
# a style requests at render time, so there's no need for a separate
# assets/ copy per size).
# ---------------------------------------------------------------------------
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def asset_path(rel_path):
    return os.path.join(_SCRIPT_DIR, rel_path)


# ---------------------------------------------------------------------------
# Recoloured per-accent icon cache. Written to a fresh OS temp directory,
# created lazily and cleaned up automatically at process exit (atexit) --
# NOT cached permanently in assets/icons/, because a permanent cache only
# ever asks "does this file exist", never "is it still correct", which
# let a stale wrong-colour file survive a later code fix (real bug, Aug
# 2026). Shared across every size script that imports this module: since
# recolouring is size-independent, a "house_banner_navy.png" generated by
# bin_sticker_small.py can be safely reused if bin_sticker_medium.py asks
# for the exact same master + colour, rather than re-running the recolour
# loop twice for identical output.
# ---------------------------------------------------------------------------
_ICON_CACHE_DIR = None


def get_icon_cache_dir():
    global _ICON_CACHE_DIR
    if _ICON_CACHE_DIR is None:
        _ICON_CACHE_DIR = tempfile.mkdtemp(prefix="bin_sticker_icons_")
        atexit.register(shutil.rmtree, _ICON_CACHE_DIR, ignore_errors=True)
    return _ICON_CACHE_DIR


def cached_icon_path(name):
    """Path for a recoloured icon variant inside this run's temp cache
    (e.g. name='house_banner_black.png'). Distinct from asset_path, which
    resolves permanent, real source assets."""
    return os.path.join(get_icon_cache_dir(), name)


def recolour_silhouette(in_path, out_path, hex_color):
    """Recolours a single-colour silhouette PNG to any hex value, using
    its own alpha channel as the mask (so anti-aliased edges stay clean)."""
    img = Image.open(in_path).convert("RGBA")
    r, g, b = tuple(int(hex_color.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4))
    pixels = img.load()
    for y in range(img.height):
        for x in range(img.width):
            _, _, _, a = pixels[x, y]
            if a > 0:
                pixels[x, y] = (r, g, b, a)
    img.save(out_path)


# ---------------------------------------------------------------------------
# Colours
# ---------------------------------------------------------------------------
BG = "#FFFFFF"
INK = "#111111"
INK_MUTED = "#555555"
GUIDE = "#CCCCCC"
PAD = 2 * mm  # inset of the design/border from the cut edge, shared default
BORDER_CORNER_RADIUS = 7 * mm  # rounded-corner radius for draw_border's
# accent-colour printed border (Sep 2026, revised) -- matches the middle
# option of the physical 3-in-1 corner rounder punch (4mm/7mm/10mm), NOT
# the original 2mm chosen from a pure visual-preference test. That 2mm
# choice was made before checking the punch tool's actual fixed radii --
# 2mm isn't achievable with any real punch option, so the software
# border now matches a size the physical tool can actually produce.
# 7mm chosen as the middle ground given unresolved prior test data
# (Material-Test-Plan.md, Aug 2026, Stickiply material only): 4mm/7mm
# jammed the punch, 10mm avoided jamming but tore the material -- 7mm
# splits the difference between the two reported failure modes rather
# than being a confirmed-safe choice. Re-test on real Cricut-brand
# material before committing to bulk production.
#
# NOT the grey cut-guide line in draw_base, which stays sharp-cornered
# on purpose (it's a cutting reference, not part of the finished
# design). See draw_border's own docstring for which styles this does
# and doesn't apply to.

ACCENTS = {
    "black":      INK,
    "charcoal":   "#2C2C2A",
    "forest":     "#2F5233",
    "navy":       "#1F3A5F",
    "terracotta": "#B0532E",
    "berry":      "#7A2E4D",
    "mustard":    "#B4841F",
}

# Second palette for a different production method: printing coloured ink
# on CLEAR vinyl and applying direct to a coloured bin, no white card
# behind it (Technique F in Idea-Board-Solutions-Reference.md). These 5
# were chosen for visibility on dark bin plastic (green/brown deliberately
# avoided so they don't blend into 2 of the 3 most common bin colours) --
# they are NOT a stylistic alternative to ACCENTS, they solve a different
# problem (opacity on clear film) and are picked for that, not for how
# they look on a white card.
#
# STATUS: not yet production-validated. Bin-Sticker-Material-Test-Plan.md
# Addendum 2 (visibility on black/green/brown) and Addendum 3 (UV/scratch
# durability on clear film specifically) are both still pending physical
# testing as of this palette being added to the script.
CLEAR_VINYL_ACCENTS = {
    "golden_yellow": "#F2B705",
    "cream":         "#F5E8C8",
    "burnt_amber":   "#D9782E",
    "powder_blue":   "#8FB8DE",
    "dusty_rose":    "#E08A73",
}


def resolve_accent(accent_key, default="navy"):
    """Looks up an accent key in ACCENTS first, then CLEAR_VINYL_ACCENTS,
    so any style function can accept a key from either palette. Falls
    back to ACCENTS[default] if the key isn't found in either."""
    if accent_key in ACCENTS:
        return ACCENTS[accent_key]
    if accent_key in CLEAR_VINYL_ACCENTS:
        return CLEAR_VINYL_ACCENTS[accent_key]
    return ACCENTS[default]


# ---------------------------------------------------------------------------
# Shared icon-asset registry -- "floral", "house", "paw" only. These 3
# vector fallbacks (and their matching illustrated-art upgrade paths) are
# used across multiple styles in multiple size scripts (the wreath
# family, house_banner/p27/p47, and the duck/dog/cat families +
# p21_paw_trail respectively), so they live here rather than being
# duplicated per size script. A style-specific illustrated asset (e.g.
# house_banner_master.png, p21_paw_trail_icon.png) is NOT a generic
# fallback and stays defined in its own size script instead.
# ---------------------------------------------------------------------------
ICON_ASSETS = {
    "floral": "assets/icons/flower_icon.png",
    "house": "assets/icons/house_icon.png",
    "paw": "assets/icons/paw_icon.png",
}


def draw_icon(c, cx, cy, size, color, style_key, vector_fn):
    """Use the illustrated PNG in ICON_ASSETS if it exists on disk,
    otherwise fall back to the built-in vector shape. This is the single
    switchover point — once real artwork lands at the path above, every
    sticker using that style upgrades automatically."""
    rel_path = ICON_ASSETS.get(style_key)
    if rel_path and os.path.exists(asset_path(rel_path)):
        img = ImageReader(asset_path(rel_path))
        c.drawImage(img, cx - size / 2, cy - size / 2, size, size,
                    mask='auto', preserveAspectRatio=True)
    else:
        vector_fn(c, cx, cy, size, color)


# ---------------------------------------------------------------------------
# Base layer (every sticker) and border layer (drawn LAST so colour-block
# styles never paint over it). w/h are REQUIRED (no default card size) --
# this module doesn't know which size script is calling it, so a size
# script that forgets to pass its own w/h should get a loud TypeError,
# not a silent wrong-sized card.
# ---------------------------------------------------------------------------

def draw_base(c, ox, oy, w, h):
    c.setFillColor(HexColor(BG))
    c.rect(ox, oy, w, h, fill=1, stroke=0)

    c.setStrokeColor(HexColor(GUIDE))
    c.setLineWidth(0.4)
    c.rect(ox, oy, w, h, fill=0, stroke=1)

    tick = 3 * mm
    for cx, cy, dx, dy in [
        (ox, oy, -tick, -tick), (ox + w, oy, tick, -tick),
        (ox, oy + h, -tick, tick), (ox + w, oy + h, tick, tick),
    ]:
        c.line(cx, cy, cx + dx, cy)
        c.line(cx, cy, cx, cy + dy)


# Colour deliberately distinct from GUIDE (the real, precise cut line) so
# the two are never confused when hand-trimming by eye -- GUIDE is what
# the Cricut/scissors should ultimately follow exactly; this is the
# looser, "cut somewhere out here" line.
TRIM_MARGIN_GUIDE_COLOR = "#4A90D9"


def draw_trim_margin_guide(c, ox, oy, w, h, margin):
    """Optional, opt-in guide for the "hand-trim into separate pieces,
    then cut precisely on the Cricut" paper-test workflow (Sep 2026) --
    draws a dashed rectangle OUTSET from the card's true boundary by
    `margin`, well outside the real cut line drawn by draw_base above.

    This is deliberately a SEPARATE function, not folded into draw_base,
    and deliberately not called by default anywhere -- it only exists to
    mark where it's safe to hand-trim with scissors/guillotine BEFORE
    the precise machine cut, leaving real margin for placement error on
    the mat. It has no role in the finished product and should never
    appear on a real customer order.

    margin: how far OUTSIDE the true card edge to draw this line, e.g.
    2.5*mm for a 2.5mm trim allowance each side."""
    c.setStrokeColor(HexColor(TRIM_MARGIN_GUIDE_COLOR))
    c.setLineWidth(0.4)
    c.setDash(2, 2)
    c.rect(ox - margin, oy - margin, w + 2 * margin, h + 2 * margin, fill=0, stroke=1)
    c.setDash()


def draw_border(c, ox, oy, order, weight="single", *, w, h, pad=None):
    """pad overrides the shared PAD cutting-tolerance inset for this call
    only -- used when one style needs a different cut-to-border margin
    than the rest. Defaults to the shared PAD if not given.

    w/h are keyword-only and required (no default) -- every real call
    site already passes them as w=.../h=... keywords (a holdover from
    the original single-file signature, where they had defaults), so
    keyword-only here doesn't break any call site, it just makes the
    lack of a default explicit and stops `weight`'s position from ever
    colliding with a keyword `w=` the way a plain positional w would.

    Corners are rounded at BORDER_CORNER_RADIUS (7mm as of Sep 2026,
    matching the middle option on the physical 3-in-1 corner punch --
    see the constant's own comment). This does NOT touch every style's
    border -- p09a_borderless has no border at all by design, and
    p25b's corner-bracket artwork is bespoke and doesn't use a radius
    concept at all. p25_landscape_flourish draws its own thicker
    roundRect rather than calling this function, but uses the same
    7mm punch radius via P25_BORDER_RADIUS. Every other bordered
    style goes through this function and picks up the 7mm rounding
    automatically."""
    if pad is None:
        pad = PAD
    accent = HexColor(resolve_accent(order.get("accent", "charcoal")))
    c.setStrokeColor(accent)
    c.setLineWidth(1.1)
    c.setDash()
    c.roundRect(ox + pad, oy + pad, w - 2 * pad, h - 2 * pad, BORDER_CORNER_RADIUS, fill=0, stroke=1)
    if weight == "double":
        c.setLineWidth(0.5)
        inset = pad + 2.2 * mm
        c.roundRect(ox + inset, oy + inset, w - 2 * inset, h - 2 * inset, BORDER_CORNER_RADIUS, fill=0, stroke=1)
    elif weight == "dashed":
        c.setDash(2, 2)
        c.setLineWidth(0.7)
        inset = pad + 2.0 * mm
        c.roundRect(ox + inset, oy + inset, w - 2 * inset, h - 2 * inset, BORDER_CORNER_RADIUS, fill=0, stroke=1)
        c.setDash()


# ---------------------------------------------------------------------------
# Vector icon helpers — plain shapes only, no external art. Each is
# self-contained (no card-size dependency, just a `size` param), so they
# work identically at any print size.
# ---------------------------------------------------------------------------

def draw_flower_icon(c, cx, cy, size, color):
    c.saveState()
    # flanking leaves, drawn first so the flower sits on top
    c.setFillColor(HexColor(color))
    leaf_w, leaf_h = size * 0.55, size * 0.20
    for side in (-1, 1):
        c.saveState()
        c.translate(cx + side * size * 0.5, cy - size * 0.08)
        c.rotate(side * 25)
        c.ellipse(-leaf_w / 2, -leaf_h / 2, leaf_w / 2, leaf_h / 2, fill=1, stroke=0)
        c.restoreState()
    pw, ph = size * 0.35, size * 0.5
    for dx, dy in [(0, 1), (0, -1)]:
        c.ellipse(cx - pw / 2, cy + dy * size * 0.1, cx + pw / 2, cy + dy * size * 0.1 + dy * ph, fill=1, stroke=0)
    for dx, dy in [(1, 0), (-1, 0)]:
        c.ellipse(cx + dx * size * 0.1, cy - pw / 2, cx + dx * size * 0.1 + dx * ph, cy + pw / 2, fill=1, stroke=0)
    c.setFillColor(HexColor("#4A3B1D"))
    r = size * 0.13
    c.ellipse(cx - r, cy - r, cx + r, cy + r, fill=1, stroke=0)
    c.restoreState()


def draw_house_icon(c, cx, cy, size, color):
    c.saveState()
    c.setFillColor(HexColor(color))
    w, h = size * 0.8, size * 0.5
    c.rect(cx - w / 2, cy - h / 2, w, h, fill=1, stroke=0)
    p = c.beginPath()
    p.moveTo(cx - w / 2 - size * 0.08, cy + h / 2)
    p.lineTo(cx, cy + h / 2 + size * 0.32)
    p.lineTo(cx + w / 2 + size * 0.08, cy + h / 2)
    p.close()
    c.drawPath(p, fill=1, stroke=0)
    c.setFillColor(white)
    dw, dh = w * 0.22, h * 0.55
    c.rect(cx - dw / 2, cy - h / 2, dw, dh, fill=1, stroke=0)
    c.restoreState()


def draw_paw_icon(c, cx, cy, size, color):
    c.saveState()
    c.setFillColor(HexColor(color))
    c.ellipse(cx - size * 0.22, cy - size * 0.20, cx + size * 0.22, cy + size * 0.12, fill=1, stroke=0)
    toe_r = size * 0.10
    for dx, dy in [(-0.22, 0.22), (-0.08, 0.30), (0.08, 0.30), (0.22, 0.22)]:
        c.ellipse(cx + dx * size - toe_r, cy + dy * size - toe_r,
                   cx + dx * size + toe_r, cy + dy * size + toe_r, fill=1, stroke=0)
    c.restoreState()


def draw_center_flourish(c, cx, y, icon_rel_path, width, color=INK):
    """Draws a flourish as a real image asset (extracted from the
    reference PNG via icon-silhouette-extraction, then recoloured/cached
    exactly like the P02 house icon), rather than a hand-drawn or
    hand-traced vector approximation. width is the desired real-world
    width in points/mm; height is derived from the source PNG's own
    aspect ratio so it isn't stretched."""
    master = asset_path(icon_rel_path)
    if not os.path.exists(master):
        return  # asset missing -- draw nothing rather than a wrong placeholder
    name = os.path.splitext(os.path.basename(icon_rel_path))[0]
    coloured_path = cached_icon_path(f"{name}_{color.lstrip('#')}.png")
    if not os.path.exists(coloured_path):
        recolour_silhouette(master, coloured_path, color)
    img = ImageReader(coloured_path)
    iw, ih = img.getSize()
    height = width * ih / iw
    c.drawImage(img, cx - width / 2, y - height / 2, width=width, height=height, mask="auto")


# ---------------------------------------------------------------------------
# Text auto-fit and curved text -- both fully generic (no card-size
# dependency; max_width/curve_coeffs are passed in explicitly by the
# caller).
# ---------------------------------------------------------------------------

def fit_font_size(text, font, max_size, min_size, max_width, step=0.5):
    """Shrinks from max_size until `text` fits within max_width (points),
    or hits min_size."""
    size = max_size
    while size > min_size and stringWidth(text, font, size) > max_width:
        size -= step
    return round(size, 1)


# Adobe AFM CapHeight values, used to centre house-number/street-name
# text against its actual ink height rather than the font's full
# ascent+descent box (which reserves space for descenders that digit
# strings and .upper()'d street names never use, pulling a
# getAscentDescent-based centre too low). Standard published values, not
# derived per-size -- correct at any card size.
TIMES_BOLD_CAP_HEIGHT_RATIO = 0.676
HELVETICA_BOLD_CAP_HEIGHT_RATIO = 0.718


def draw_curved_text(c, text, cx, baseline, font, size, color,
                      icon_x_left, icon_scale, curve_fn, curve_coeffs):
    """Draws `text` centred on cx, following curve_fn (an icon-local-px
    -> icon-local-px function). `baseline` is where the centre character
    sits; curvature is a per-character offset relative to that, so this
    degrades gracefully to flat text if curve_fn is ~constant.

    `curve_coeffs` (a, b, c of the same quadratic curve_fn implements) is
    used ONLY for the per-character rotation angle (the fit's slope at
    that x). Passed explicitly rather than read from a module-level
    constant, so two different callers (e.g. P02's banner curve and a
    future P06-equivalent) never accidentally share rotation math."""
    total_w = stringWidth(text, font, size)
    x_cursor = cx - total_w / 2
    x_img_at_cx = (cx - icon_x_left) / (icon_scale * mm)
    ref_mid_px = curve_fn(x_img_at_cx)
    a, b, _ = curve_coeffs

    c.setFillColor(HexColor(color))
    c.setFont(font, size)
    for ch in text:
        cw = stringWidth(ch, font, size)
        x_char = x_cursor + cw / 2
        x_img = (x_char - icon_x_left) / (icon_scale * mm)
        mid_px = curve_fn(x_img)
        delta_y = -(mid_px - ref_mid_px) * icon_scale * mm  # image y-down -> reportlab y-up
        slope_img = 2 * a * x_img + b
        angle_deg = -math.degrees(math.atan(slope_img))
        c.saveState()
        c.translate(x_char, baseline + delta_y)
        c.rotate(angle_deg)
        c.drawCentredString(0, 0, ch)
        c.restoreState()
        x_cursor += cw


# ---------------------------------------------------------------------------
# Generic grid sheet layout -- the piece that makes per-size scripts
# possible without duplicating layout math. Every size script calls this
# with its OWN card_w/card_h and grid shape (cols x rows); this function
# doesn't know or care which size it's laying out.
#
# IMPORTANT ASYMMETRY THIS REPLACES: the original single-file design
# always assumed a 2x2 (4-up) grid, because every style that existed so
# far happened to fit that shape. Medium (210x140mm) breaks that
# assumption -- it's 2-per-sheet STACKED (1 col x 2 rows), not 2x2 --
# so this function takes cols/rows explicitly rather than hardcoding 2x2.
# ---------------------------------------------------------------------------

def sheet_layout(card_w, card_h, page_w, page_h, cols, rows, margin_x=None, margin_y=None):
    """Computes the grid of card bottom-left origins for a cols x rows
    grid of card_w x card_h cards on a page_w x page_h page.

    margin_x: explicit LEFT margin in points, for an asymmetric layout
    (e.g. the small size's 14mm left margin for lamination slack). If
    None, centred automatically.

    margin_y: explicit TOP margin in points (the gap above the FIRST/
    top row) -- NOT the bottom margin, despite the name possibly
    suggesting otherwise. Rows are generated top-row-first to match the
    "top-left, top-right, ..." position ordering documented below, so
    margin_y anchors that same top edge. If None, centred automatically.
    Confirmed directly (Sep 2026): margin_y=14mm on a 2-row layout with
    17mm total slack produces a 14mm gap above the top row and a 3mm gap
    below the bottom row, not the reverse.

    Positions are returned top-row-first, left-to-right (matching the
    original single-file convention: top-left, top-right, ..., bottom-
    left, bottom-right)."""
    total_w = cols * card_w
    total_h = rows * card_h
    if margin_x is None:
        margin_x = (page_w - total_w) / 2
    else:
        available = page_w - total_w
        assert margin_x <= available, (
            f"margin_x ({margin_x / mm}mm) exceeds the {available / mm}mm of "
            f"horizontal slack available for a {cols}x{rows} grid of "
            f"{card_w / mm}x{card_h / mm}mm cards on a {page_w / mm}mm-wide "
            f"page -- reduce margin_x or this grid can't fit at this size."
        )
    if margin_y is None:
        margin_y = (page_h - total_h) / 2
    else:
        available_y = page_h - total_h
        assert margin_y <= available_y, (
            f"margin_y ({margin_y / mm}mm) exceeds the {available_y / mm}mm of "
            f"vertical slack available for a {cols}x{rows} grid of "
            f"{card_w / mm}x{card_h / mm}mm cards on a {page_h / mm}mm-tall "
            f"page -- reduce margin_y or this grid can't fit at this size."
        )
    positions = []
    for r in range(rows):
        y = page_h - margin_y - card_h - r * card_h
        for col in range(cols):
            x = margin_x + col * card_w
            positions.append((x, y))
    return margin_x, margin_y, positions


def render_sheet_grid(orders, out_path, card_w, card_h, cols, rows, draw_fn,
                       page_size, margin_x=None, margin_y=None, caption=False,
                       style_labels=None):
    """Renders up to cols*rows cards in a grid on one page.

    draw_fn(c, ox, oy, order): draws one card at the given origin --
    normally a size script's own draw_sticker.
    page_size: explicit (w, h) in points. Deliberately NOT auto-derived
    from card_w/card_h here (a card being wider than tall does NOT mean
    its SHEET should be landscape -- Medium's 210x140mm card sits on a
    PORTRAIT page, stacked vertically, which is exactly the case that
    would break an auto "landscape if card_w > card_h" heuristic). Each
    size script passes its own real page orientation explicitly.
    style_labels: optional dict for the `caption=True` bottom-margin
    label (order["style"] -> display string); falls back to the raw key.
    """
    if len(orders) > cols * rows:
        raise ValueError(
            f"render_sheet_grid got {len(orders)} orders but the {cols}x{rows} "
            f"grid only holds {cols * rows} -- split into multiple calls."
        )
    page_w, page_h = page_size
    _, _, positions = sheet_layout(card_w, card_h, page_w, page_h, cols, rows, margin_x, margin_y)

    c = canvas.Canvas(out_path, pagesize=page_size)
    for order, (x, y) in zip(orders, positions):
        draw_fn(c, x, y, order)
        if caption and "style" in order:
            c.setFont("Helvetica", 6)
            c.setFillColor(HexColor("#888888"))
            label = (style_labels or {}).get(order["style"], order["style"])
            c.drawCentredString(x + card_w / 2, 2.5 * mm, label)
    c.showPage()
    c.save()


def render_gallery_grid(style_keys, sample_order, out_path, card_w, card_h, cols, rows,
                         draw_fn, page_size, style_labels=None,
                         margin_x=None, margin_y=None):
    """One card per style in style_keys, paginated cols*rows-up.
    draw_fn(c, ox, oy, order) draws one card; order['style'] is set per
    call from style_keys. See render_sheet_grid for why page_size is
    required rather than auto-derived.

    margin_x/margin_y are forwarded to sheet_layout so a size script can
    keep the same asymmetric print margins on galleries as on sheets
    (e.g. Small's 14mm left). Default None still centres the grid."""
    page_w, page_h = page_size
    _, _, positions = sheet_layout(
        card_w, card_h, page_w, page_h, cols, rows, margin_x, margin_y,
    )
    per_page = cols * rows

    c = canvas.Canvas(out_path, pagesize=page_size)
    for i, style in enumerate(style_keys):
        slot = i % per_page
        if i > 0 and slot == 0:
            c.showPage()
        x, y = positions[slot]
        order = dict(sample_order)
        order["style"] = style
        draw_fn(c, x, y, order)
        c.setFont("Helvetica", 6)
        c.setFillColor(HexColor("#888888"))
        label = (style_labels or {}).get(style, style)
        c.drawCentredString(x + card_w / 2, 2.5 * mm, label)
    c.showPage()
    c.save()


# ---------------------------------------------------------------------------
# Cricut placement-reference SVG -- OPTIONAL, never part of a real print
# job. Purpose: a visual aid loaded into Design Space to help position
# real vector cut shapes by eye against a picture of the actual printed
# sheet, since cut-only mode has no camera/registration to do this
# automatically (see chat history, "Custom bin sticker sheet layout
# specifications" follow-up, for the full story of why this exists and
# the several rounds of correction that arrived at this design).
#
# 4 layers, each a distinct colour -- Design Space automatically splits
# an imported multi-colour SVG into one layer per colour on import, so
# no special grouping syntax is needed beyond genuinely using 4 colours:
#   GREEN  -- the full physical page boundary (sharp corners -- it's the
#             page itself, not a sticker)
#   GREY   -- each card's true edge (sharp corners) + corner tick marks,
#             matching draw_base's own convention exactly
#   BLACK  -- each card's REAL accent-border outline, at that specific
#             style's own true pad + radius (NOT a generic guess --
#             computed from the same values that style's own
#             draw_border call actually uses, via style_pad_radius)
#   RED    -- kiss-cut reference, per card, fixed 1mm inset from the true
#             edge (grey) -- guaranteed to sit outside every style's own
#             border since 1mm is less than the smallest real pad (2mm),
#             confirmed directly rather than assumed
#
# Deliberately LINES ONLY -- no illustrated design content (icons, house
# numbers, street names). This is a placement aid, not something meant
# to preview the finished design, and the full illustrated content would
# be far more complex to convert to clean SVG for no real benefit here.
#
# UNITS: unitless coordinates (1 user unit = 1px @ 96dpi) -- the SVG
# spec's own default, chosen after DIRECT TESTING found explicit "mm"
# unit suffixes import at an unpredictable wrong scale in Design Space
# (confirmed: one file imported ~2.77x too large with "mm" suffixes).
# Unitless coordinates fared better in practice but were STILL observed
# to import at an unpredictable wrong scale once (~1.3x too large) on a
# separate file -- ALWAYS verify the imported size in Design Space's own
# Size panel after upload (should read the true page size, e.g. 29.7 x
# 21.0cm for Small) and manually correct via the aspect-locked Size
# field if it's off. This isn't a one-time fix, it's a check to make
# every time -- Design Space's import scale has not been reliable.
# ---------------------------------------------------------------------------

_MM_TO_PX = 96 / 25.4  # SVG spec default: 1 user unit = 1px = 1/96 inch


def _svg_px(v_points):
    """Convert an internal reportlab-points value (i.e. anything already
    multiplied by the `mm` scale factor, like every other measurement in
    this codebase) to the unitless SVG coordinate this file uses."""
    return round((v_points / mm) * _MM_TO_PX, 3)


def render_cricut_reference_svg(orders, out_path, card_w, card_h, cols, rows,
                                 page_size, style_pad_radius,
                                 margin_x=None, margin_y=None,
                                 kiss_cut_inset=1 * mm, tick=3 * mm):
    """Writes an SVG placement-reference image (see module comment above
    for the full rationale) -- NOT a PDF, never for real cutting.

    orders: list of order dicts, one per card actually on this sheet
    (must each have a "style" key) -- NOT necessarily all styles this
    size supports, just whichever ones this specific reference is for.
    Uses the same sheet_layout positions render_sheet_grid would for
    these same cols/rows/margins, so it matches a real print exactly.

    style_pad_radius: dict, style_key -> (pad, radius) or None.
    "pad"/"radius" must be THAT STYLE'S OWN real accent-border values
    (not a generic default) -- computed once per size script from each
    style's actual _draw_border call, so the black reference line
    genuinely matches what prints, not a guess. None means this style
    has no real border (e.g. p09a_borderless, or a style like p25b
    whose border is too structurally different from a simple rounded
    rectangle to represent this way) -- the black layer is simply
    skipped for that specific card; grey and red still render as usual.
    """
    if len(orders) > cols * rows:
        raise ValueError(
            f"render_cricut_reference_svg got {len(orders)} orders but the "
            f"{cols}x{rows} grid only holds {cols * rows}."
        )
    page_w, page_h = page_size
    _, _, positions = sheet_layout(card_w, card_h, page_w, page_h, cols, rows, margin_x, margin_y)

    def rect_el(x, y, w, h):
        return (f'<rect x="{_svg_px(x)}" y="{_svg_px(y)}" width="{_svg_px(w)}" '
                f'height="{_svg_px(h)}" fill="none" stroke-width="1.5" />')

    def roundrect_el(x, y, w, h, r):
        return (f'<rect x="{_svg_px(x)}" y="{_svg_px(y)}" width="{_svg_px(w)}" '
                f'height="{_svg_px(h)}" rx="{_svg_px(r)}" ry="{_svg_px(r)}" '
                f'fill="none" stroke-width="1.5" />')

    green_shapes = [rect_el(0, 0, page_w, page_h)]

    grey_shapes = []
    black_shapes = []
    red_shapes = []
    for order, (x_rl, y_rl) in zip(orders, positions):
        # Flip bottom-left/y-up (reportlab, matches every other position
        # in this codebase) to top-left/y-down (SVG) -- same flip as the
        # already-confirmed working small_cut_lines.svg.
        x = x_rl
        y = page_h - y_rl - card_h

        grey_shapes.append(rect_el(x, y, card_w, card_h))
        for cx, cy, dx, dy in [
            (x, y, -tick, -tick), (x + card_w, y, tick, -tick),
            (x, y + card_h, -tick, tick), (x + card_w, y + card_h, tick, tick),
        ]:
            grey_shapes.append(f'<line x1="{_svg_px(cx)}" y1="{_svg_px(cy)}" '
                                f'x2="{_svg_px(cx + dx)}" y2="{_svg_px(cy)}" stroke-width="1.5" />')
            grey_shapes.append(f'<line x1="{_svg_px(cx)}" y1="{_svg_px(cy)}" '
                                f'x2="{_svg_px(cx)}" y2="{_svg_px(cy + dy)}" stroke-width="1.5" />')

        style = order["style"]
        pad_radius = style_pad_radius.get(style)
        if pad_radius is not None:
            pad, radius = pad_radius
            black_shapes.append(roundrect_el(x + pad, y + pad, card_w - 2 * pad, card_h - 2 * pad, radius))

        i = kiss_cut_inset
        # Use this style's own radius for red too if known, otherwise a
        # plain rectangle (0 radius) -- red should still visually relate
        # to the same corner style as black where that's known.
        red_radius = pad_radius[1] if pad_radius is not None else 0
        red_shapes.append(roundrect_el(x + i, y + i, card_w - 2 * i, card_h - 2 * i, red_radius))

    svg = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{_svg_px(page_w)}" height="{_svg_px(page_h)}"\n'
        f'     viewBox="0 0 {_svg_px(page_w)} {_svg_px(page_h)}">\n'
        f'  <g id="green_page_frame" stroke="#00A651">\n    ' + "\n    ".join(green_shapes) + "\n  </g>\n"
        f'  <g id="grey_cut_guide" stroke="#CCCCCC">\n    ' + "\n    ".join(grey_shapes) + "\n  </g>\n"
        f'  <g id="black_accent_border" stroke="#111111">\n    ' + ("\n    ".join(black_shapes) if black_shapes else "") + "\n  </g>\n"
        f'  <g id="red_kiss_cut" stroke="#E8112D">\n    ' + "\n    ".join(red_shapes) + "\n  </g>\n"
        "</svg>\n"
    )
    with open(out_path, "w") as f:
        f.write(svg)
